name: actiondoc
description: >-
  Generates documentation from your GitHub Action's `action.yml`

inputs:
  template-filename:
    description: >-
      The path to the ERB template to use to generate the documentation.
    required: false
  output-filename:
    description: >-
      The filename to save the output to. If not specified, simply prints to standard output.
    required: false
  path-to-action-yml:
    description: >-
      The path to the `action.yml` file to generate documentation for. If not specified, assumes `action.yml`.
    required: false
  working-directory:
    description: >-
      The directory to perform the action in, if not $GITHUB_WORKSPACE
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo working-directory: ${{ inputs.working-directory || github.workspace }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory || github.workspace }}
    - shell: bash
      working-directory: ${{ inputs.working-directory || github.workspace }}
      env:
        TEMPLATE_FILENAME: ${{ inputs.template-filename }}
        OUTPUT_FILENAME: ${{ inputs.output-filename }}
        PATH_TO_ACTION_YML: ${{ inputs.path-to-action-yml }}
      run: |
        echo TEMPLATE_FILENAME: "${TEMPLATE_FILENAME}"
        echo OUTPUT_FILENAME: "${OUTPUT_FILENAME}"
        echo PATH_TO_ACTION_YML: "${PATH_TO_ACTION_YML}"

        rake build
        gem install pkg/actiondoc-0.4.0.gem
        set --
        if [[ -n "${TEMPLATE_FILENAME}" ]]; then
          set -- "$@" --template "${TEMPLATE_FILENAME}"
        fi
        if [[ -n "${PATH_TO_ACTION_YML}" ]]; then
          set -- "$@" "${PATH_TO_ACTION_YML}"
        fi
        if [[ -z "${OUTPUT_FILENAME}" ]]; then
          ( set -x; actiondoc "$@" )
        else
          ( set -x; actiondoc "$@" > "${OUTPUT_FILENAME}" )
        fi

branding:
  icon: book-open
  color: purple
