name: Generate GitHub Action documentation
description: >-
  Generates documentation from your GitHub Action's `action.yml`

inputs:
  path-to-action-yml:
    description: >-
      The path to the `action.yml` file to generate documentation for.
    required: false
  working-directory:
    description: >-
      The directory to perform the action in, if not $GITHUB_WORKSPACE
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: |
        echo working-directory: ${{ inputs.working-directory || github.workspace }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory || github.workspace }}
    - shell: bash
      working-directory: ${{ inputs.working-directory || github.workspace }}
      run: |
        ls -l generate.rb
        ruby generate.rb > README.md
        cat README.md
