name: Action Tests
on: push

jobs:
  test-with-defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -l .
      - name: Given
        run: if [ -f README.md ]; then rm README.md; fi
      - name: Test with defaults
        uses: ./.
        with:
          output-filename: README.md
      - run: |
          ls -l .
      - name: Assertions
        run: |
          cat README.md
          [ -f README.md ] && diff README.md test/fixtures/expected-README.md.no-template

  test-with-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -l .
      - name: Given
        run: if [ -f README.md ]; then rm README.md; fi
      - name: Test with defaults
        uses: ./.
        with:
          template-filename: test/fixtures/test-README.md.erb
          output-filename: README.md
      - run: |
          ls -l .
      - name: Assertions
        run: |
          cat README.md
          [ -f README.md ] && diff --strip-trailing-cr README.md test/fixtures/expected-README.md.with-template
