name: Action Tests
on: push

jobs:
  test-with-defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -l .
      - name: Given
        run: if [ -f README.md ]; then rm README.md; fi
      - name: Test with defaults
        uses: ./.
      - run: |
          ls -l .
      - name: Assertions
        run: |
          cat README.md
          [ -f README.md ] && diff README.md .github/workflows/README.md.expected
