name: Build Docker Image
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
    paths:
      - "!.github/workflows/**"
      - .github/workflows/docker-build.yml
      - "lib/**"
      - "exe/**"
      - actiondoc.gemspec
      - Dockerfile
      - Gemfile
      - Rakefile

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # So now you can use Actions' own caching!
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ inputs.git-hash || github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          rake build
      - name: Build and push tag or branch
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
      - name: Build and push latest on tag only
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

  docker-test-with-template:
    needs: docker-build
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Given
        run: if [ -f README.md ]; then rm README.md; fi
      - name: Test with defaults
        run: |
          actiondoc --template templates/README.md.erb > README.md
      - name: Assertions
        run: |
          cat README.md
          [ -f README.md ] && diff README.md .github/workflows/README.md.with-template
