name: Action Tests
on:
  push:
    branches:
      - tags/**
    paths:
      - "!.github/workflows/**"
      - .github/workflows/docker-build.yml
      - "lib/**"
      - "exe/**"
      - actiondoc.gemspec
      - Dockerfile
      - Gemfile
      - Rakefile

jobs:
  docker-test-with-template:
    runs-on: ubuntu-latest
    container: actiondoc
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -l .
      - name: Given
        run: if [ -f README.md ]; then rm README.md; fi
      - name: Test with defaults
        run: |
          actiondoc --template templates/README.md.erb > README.md
      - run: |
          ls -l .
      - name: Assertions
        run: |
          cat README.md
          [ -f README.md ] && diff README.md .github/workflows/README.md.with-template
