name: Generate README
on:
  push:
    branches:
      - main
    paths:
      - action.yml
      - templates/**

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: if [ -f README.md ]; then rm README.md; fi
      - name: Generate README
        uses: ./.
        with:
          template-filename: templates/README.md.erb
          output-filename: README.md
      - run: |
          cat README.md
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
